# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('jobId', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=200)),
                ('salary', models.CharField(default='', max_length=50)),
                ('salaryPer', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('sponsored', models.BooleanField(default=False, max_length=50)),
                ('expired', models.BooleanField(default=False, max_length=50)),
                ('expireInDays', models.IntegerField(default=0)),
                ('postedDaysAgo', models.IntegerField(default=0)),
            ],
        ),
    ]
